databases:
  - name: postgres
    ipAllowList: []
    databaseName: xmas-radio-24
    user: xmas-radio-24

services:
  - type: web
    name: xmas-radio-24
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
